print("please Provide your credentials for login..........")
print("Check your Username and Password!")
print("Edit the changes")
print("Click on the save on file to save the changes..!")
print(Click on Save as to save your new file")
print("THANK YOU......!!!!")
